blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('create/', views.CreateForm.as_view(), name='create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import PostListView

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='auth')),
    path('post/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models


class Post(models.Model):
    author = models.ForeignKey(
        verbose_name='저자',
        to='users.User',
        editable=False,
        on_delete=models.DO_NOTHING,
    )
    title = models.CharField(
        verbose_name='제목',
        max_length=255,
    )
    contents = models.TextField(
        verbose_name='내용',
        default='',
    )
    create_at = models.DateTimeField(
        verbose_name='생성일',
        auto_now_add=True,
    )
    update_at = models.DateTimeField(
        verbose_name='수정일',
        auto_now=True,
    )

    def __str__(self):
        return '<Blog %s>' % self.id

    class Meta:
        db_table = 'blog'
        verbose_name = '게시글'
        verbose_name_plural = '게시글들'

blog/forms.py
from django import forms


class CreateForm(forms.Form):
    author = forms.CharField(
        error_messages={
            'required': '글쓴이 정보가 필요합니다.'
        },
        widget=forms.HiddenInput,
        label='글쓴이',
        required=True,
    )
    title = forms.CharField(
        error_messages={
            'required': '제목을 입력해주세요.'
        },
        max_length=255,
        label='제목',
        required=True,
    )
    contents = forms.CharField(
        error_messages={
            'required': '내용을 입력해주세요.'
        },
        widget=forms.Textarea,
        label='내용',
    )

    def clean(self):
        cleand_data = super().clean()
        author = cleand_data.get('author')
        title = cleand_data.get('title')

        if not (author and title):
            self.add_error('author', '글쓴이가 없습니다.')
            self.add_error('title', '제목이 없습니다.')

blog/views.py
from django.contrib import messages
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from blog.models import Post
from users.models import User
from . import forms


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'contents']
    template_name = 'blog/update.html'
    success_url = '/'

    def form_valid(self, form):
        post = Post.objects.filter(pk=self.kwargs['pk'], author=self.request.user)
        if not post.exists():  # 유효성 조건 통과
            form.add_erros('title', '수정에 실패하였습니다.')
            return super().form_invalid(form)
        return super().form_valid(form)


class PostDetailView(DetailView):
    template_name = 'blog/detail.html'
    queryset = Post.objects.all()
    context_object_name = 'post'


class PostListView(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    model = Post
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.all().order_by('-create_at')


class CreateForm(LoginRequiredMixin, FormView):
    template_name = 'blog/create.html'
    form_class = forms.CreateForm
    success_url = '/'

    def form_valid(self, form):
        author = form.cleaned_data.get('author')
        title = form.cleaned_data.get('title')
        contents = form.cleaned_data.get('contents')

        user = User.objects.filter(pk=author)

        # 존재하지 않는 유저.
        if not user.exists():
            messages.error(self.request, '글쓰기에 실패하였습니다 탈퇴한 회원인지 확인해주세요.', extra_tags='danger')
            return super().form_invalid(form)

        post = Post(
            author=user[0],
            title=title,
            contents=contents,
        )
        post.save()

        return super().form_valid(form)

blog/templates/blog/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
글쓰기
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static '/summernote/summernote-bs4.css' %}">
<script src="{% static '/summernote/summernote-bs4.min.js' %}"></script>
<script src="{% static '/summernote/lang/summernote-ko-KR.js' %}"></script>

<script>
    $(document).ready(function() {
        $('#id_contents').summernote({
            tabsize: 4,
            height: 400,
            lang: 'ko-KR',
        });
    });
</script>
{% endblock %}

{% block contents %}
<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12 mx-auto mt-5">
                    {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                        <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show"{% endif %} role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class="card rounded-0">
                        <div class="card-header">
                            <h3 class="mb-0">게시글 작성</h3>
                        </div>
                        <div class="card-body">
                            <form class="form" method="POST">
                                {% csrf_token %}

                                {% for field in form %}
                                <div class="form-group">
                                    {% if field.is_hidden %}
                                    <input class="form-control" type="{{field.field.widget.input_type}}" id="{{field.id_for_label}}" name="{{field.name}}" placeholder="{{field.label}}" {{field.is_required}} value="{% if user.is_active %}{{user.pk}}{% endif %}" />
                                    {% else %}
                                    {% if field.name == 'contents' %}
                                    {{field}}
                                    {% else %}
                                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                                    <input class="form-control" type="{{field.field.widget.input_type}}" id="{{field.id_for_label}}" name="{{field.name}}" placeholder="{{field.label}}" {{field.is_required}} />
                                    {% endif %}
                                    {% endif %}
                                </div>
                                {% if field.errors %}
                                <span style="color: red;">{{field.errors}}</span>
                                {% endif %}
                                {% endfor %}
                                <button class="btn btn-primary btn-block mb-4">글쓰기</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}
게시글
{% endblock %}

{% block contents %}
<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12 mx-auto mt-5">
                    <div class="card rounded-0">
                        <div class="card-header">
                            <h3 class="mb-0">{{post.title}}</h3>
                            <span class="d-inline mt-2">{{post.update_at}} {% if post.create_at|date:'Y-m-d H:i:s' < post.update_at|date:'Y-m-d H:i:s' %}<strong>수정됨</strong>{% endif %}</span>
                            {% if post.author.pk == user.pk %}
                            <button class="btn btn-primary" onclick="location.href='/post/update/{{post.id}}'">수정</button>
                            {% endif %}
                        </div>
                        <div class="card-body">
                            {{post.contents|safe}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
홈
{% endblock %}

{% block header %}
<script src="{% static '/blog/js/infiniteScroll.js' %}" type="text/javascript"></script>
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div id="wrapper" class="col-md-12 pt-5">
            {% if posts %}
                {% for post in posts %}
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{{post.title}}</h2>
                        <a href="{% url 'blog:detail' post.pk %}" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                    <div class="card-footer text-muted">
                        {{post.update_at}} by
                        <span style="color: cornflowerblue;">{{post.author.username}}</span>
                    </div>
                </div>
                {% endfor %}
            {% else %}
            게시글없음
            {% endif %}
        </div>
    </div>
</div>

<script type="text/javascript">
var postWrapperId = 'wrapper';
var paginatePath = '?page=';
var lastPage = {{paginator.num_pages}};

var test = new InfiniteScroll(paginatePath, postWrapperId, lastPage);
test.detectScroll();


</script>
{% endblock %}

blog/templates/blog/update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
게시글 수정
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static '/summernote/summernote-bs4.css' %}">
<script src="{% static '/summernote/summernote-bs4.min.js' %}"></script>
<script src="{% static '/summernote/lang/summernote-ko-KR.js' %}"></script>

<script>
    $(document).ready(function() {
        $('#id_contents').summernote({
            tabsize: 4,
            height: 400,
            lang: 'ko-KR',
        });
    });
</script>
{% endblock %}

{% block jumbotron %}
<h1 class="display-5 text-center">게시글 수정</h1>
<hr class="my-4">
{% endblock %}

{% block contents %}
<div class="container my-5">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12 mx-auto mt-5">
                    {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                        <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show"{% endif %} role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class="card rounded-0">
                        <div class="card-header">
                            <h3 class="mb-0">게시글 수정</h3>
                        </div>
                        <div class="card-body">
                            <form class="form" method="POST">
                                {% csrf_token %}

                                {% for field in form %}
                                    <div class="form-group">
                                    {% if field.name == 'contents' %}
                                    {{field}}
                                    {% else %}
                                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                                    <input class="form-control" type="{{field.field.widget.input_Type}}" id="{{field.id_for_label}}" name="{{field.name}}" value="{{field.value}}">
                                    {% endif %}
                                    {% if field.errors %}
                                    <span style="color: red;">{{field.errors}}</span>
                                    {% endif %}
                                    </div>
                                {% endfor %}
                                <button class="btn btn-primary btn-block mb-4">수정</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}