blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('create/', views.CreateForm.as_view(), name='create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import PostListView

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='auth')),
    path('post/', include('blog.urls', namespace='blog')),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'auth'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('withdrawal/', views.WithdrawalView.as_view(), name='withdrawal'),
    path('logout/', views.logout_view, name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block header %}
    {% endblock %}

    <style>
        body {
          padding-top: 56px;
        }
    </style>
</head>
<body>
    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_active %}
                        <li class="nav-item">
                            <a href="{% url 'blog:create' %}" class="nav-link">글쓰기</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'auth:logout' %}" class="nav-link">로그아웃</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'auth:withdrawal' %}" class="nav-link">회원탈퇴</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'auth:login' %}" class="nav-link">로그인</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'auth:register' %}" class="nav-link">회원가입</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% endblock %}

    {% block contents %}
    {% endblock %}
</body>
</html>